FROM  almalinux:9
LABEL maintainer="John Petro"

# Install requirements.
RUN yum -y install rpm dnf-plugins-core \
 && yum -y update \
 && yum -y install \
      epel-release \
      initscripts \
      sudo \
      which \
      hostname \
      libyaml \
      python3 \
      python3-pip \
      openssh-server \
      iproute \
 && yum clean all

 # Install systemd -- See https://hub.docker.com/_/centos/
RUN rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;

# Disable requiretty.
RUN sed -i -e 's/^\(Defaults\s*requiretty\)/#--- \1/'  /etc/sudoers

# Create the ansibletest user
RUN useradd -m -G wheel -s /bin/bash ansibletest \
    && echo "ansibletest:ansibletest" | chpasswd  \
    echo 'ansibletest ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/ansibletest && \
    chmod 440 /etc/sudoers.d/ansibletest

# --- Enable SSH service so systemd starts it automatically ---
RUN systemctl enable sshd.service

# Expose SSH port
EXPOSE 22

VOLUME ["/sys/fs/cgroup"]
CMD ["/usr/lib/systemd/systemd"]